import React from "react";
import { fetchReservations, fetchSingleListing } from "@/app/libs/actions/listing.actions";
import EmptyState from "@/app/components/addons/EmptyState";
import ListingClient from "@/app/components/shared/ListingClient";
import { getCurrentUser } from "@/app/libs/actions/auth.actions";
import { Metadata } from "next";



export const metadata: Metadata = {
  title: "Listings",
  description: "Generated by create next app and typed with love.",
};

export default async function Listing({params}:{params: {id:string}}) {
  if (!params.id) return null;

  const listing = await fetchSingleListing(params.id);
  const currentUser = await getCurrentUser();
  const reservations = await fetchReservations(params.id)
  
  if (!listing) {
    return (
      <EmptyState 
        title="Listing does not exist"
        subtitle="Try changing or removing some of your filters or try again"
      />
    )
  }

  return (
    <ListingClient listing={listing} currentUser={currentUser} reservations={reservations}/>
  );
}