import type { Metadata } from "next";
import localFont from 'next/font/local'
import NavBar from "./components/shared/NavBar";
import "./globals.css";
import SignUp from "./components/forms/SignUp";
import ToasterProvider from "./providers/ToasterProvider";
import SignIn from "./components/forms/SignIn";
import { getCurrentUser } from "./libs/actions/auth.actions";
import Rent from "./components/forms/Rent";
import SearchItem from "./components/forms/SearchItem";

const barlowRegular = localFont({ src: '../public/fonts/Barlow-Regular.ttf' })

export const metadata: Metadata = {
  title: "Nomeo Coliving 1.0",
  description: "Generated by create next app and typed with love.",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const currentUser:any = await getCurrentUser();
  return (
    <html lang="en">
      <body className={barlowRegular.className}>
        <ToasterProvider/>
        <SearchItem />
        <Rent/>
        <SignIn/>
        <SignUp/>
        <NavBar currentUser={currentUser}/>
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>
    </html>
  );
}
