import React from 'react'
import { fetchAllListings } from '../libs/actions/listing.actions'
import { getCurrentUser } from '../libs/actions/auth.actions'
import EmptyState from '../components/addons/EmptyState';
import PropertyClient from '../components/shared/PropertyClient';
import { Metadata } from 'next';



export const metadata: Metadata = {
  title: "Properties",
  description: "Generated by create next app and typed with love.",
};


export default async function Properties() {
  const currentUser = await getCurrentUser();

  if (!currentUser) {
    return (
      <EmptyState
        title="Unathorized"
        subtitle="Please login"
      />
    )
  }

  const listings = await fetchAllListings({userId: currentUser.id});
   

  if (!listings || listings.length === 0) {
    return (
      <EmptyState
        title="No properties found"
        subtitle="Looks like you have no properties"
      /> 
    )
  }

  return (
    <PropertyClient currentUser={currentUser} listings={listings}/>
  )
}